rtx.defaultToAdvancedUI = True
rtx.gui.showLegacyTextureGui = True
rtx.volumetrics.froxelGridResolutionScale = 8
rtx.postfx.enable = True
rtx.volumetrics.enable = True
rtx.graphicsPreset = 2
rtx.enableReplacementAssets = True
rtx.userBrightness.userBrightness = 75
rtx.volumetrics.froxelDepthSlices = 48
